name = "online-mirror"
main = "worker.js"
compatibility_date = "2024-01-01"

[[routes]]
pattern = "online.a-i.indevs.in"
custom_domain = true

[[r2_buckets]]
binding = "PHOTO_BUCKET"
bucket_name = "photos"

[assets]
directory = "./public"
binding = "ASSETS"

[vars]
WHITELIST_IP = "" 
SYSTEM_VERSION = "9.2.1"
