name = "online-mirror"
main = "worker.js"
compatibility_date = "2024-01-01"

[[routes]]
pattern = "online.a-i.indevs.in"
custom_domain = true

[[r2_buckets]]
binding = "PHOTO_BUCKET"
bucket_name = "photos"

[assets]
directory = "."
binding = "ASSETS"

[[kv_namespaces]]
binding = "KV_DATABASE"
id = ""

[vars]
WHITELIST_IP = "149.104.139.142,154.19.243.9" 
SYSTEM_VERSION = "9.2.1"

[build]
  # 排除node_modules及所有二进制文件
  upload.exclude = [
    "node_modules/**",
    "**/*.bin",
    "**/bin/**"
  ]
