name = "online-mirror"
main = "worker.js"
compatibility_date = "2024-01-01"

[[routes]]
pattern = "online.a-i.indevs.in"
custom_domain = true

[[r2_buckets]]
binding = "PHOTO_BUCKET"
bucket_name = "photos"

[assets]
directory = "."
binding = "ASSETS"
ignore_patterns = ["/node_modules/", "/.git/"]

[[kv_namespaces]]
binding = "KV_DATABASE"
id = "1"

[vars]
WHITELIST_IP = "" 
SYSTEM_VERSION = "9.2.1"
